### ISSUE TITLE
Баг с Посохом Говнаря

### ISSUE THREAD

**Issue by MukhammatSalim** [TroExol/coolgedon#1]
## Опишите ошибку
Четкое и краткое описание ошибки.

Посохи говнаря накладываются и остаются в игре даже после конца хода. В итоге они появляются у других игроков но не могу т быть разыграны

### Шаги к воспроизведению
Шаги по воспроизведению поведения.

Взять карты "Посох говнаря", накидывать его постаянно на одного игрока пока они не закончатся. В итоге они остаются у других игроков даже при смене хода

### Ожидаемое поведение
Четкое и краткое описание того, что вы ожидаете.

Они не будут баговатся

### Окружение
 - Операционная система: Windows 11
 - Браузер: Opera GX, Google chrome
 - Устройство: ПК
 - Размер экрана: разные 16:9, 16:10 разрешения 
 - Другие детали, которые, по вашему мнению, могут повлиять.

### Дополнительно
Добавьте сюда любой другой контекст проблемы.
![изображение_2024-09-15_233030034](https://github.com/user-attachments/assets/d6aa97f6-bc5c-4573-b054-21b656fa364e)

**Comment by MukhammatSalim** [comment]
![изображение_2024-09-15_233633909](https://github.com/user-attachments/assets/8d5e1237-cc2e-45a7-b032-693044316df6)
Снова когда выпадает посох говнаря, то вместе с ним спавнять его дубликаты и считаются как один

**Comment by TroExol** [comment]
Спасибо за предоставление информации! Баг часто воспроизводимый, как временное решение посоветую обновить страницу, тогда дубликаты должны перестать появляться. Времени для работы над сайтом мало, но постараюсь исправить большинство ошибок, как появится время.

**Comment by TroExol** [comment]
Исправил в v 1.1.0
